/* tslint:disable */
/* eslint-disable */
/**
 * Quote Portal API
 * API documentation for Quote Portal
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CrmCustomersCreateRequest
 */
export interface CrmCustomersCreateRequest {
    /**
     * Customer name
     * @type {string}
     * @memberof CrmCustomersCreateRequest
     */
    name: string;
    /**
     * Customer email
     * @type {string}
     * @memberof CrmCustomersCreateRequest
     */
    email: string;
}

/**
 * Check if a given object implements the CrmCustomersCreateRequest interface.
 */
export function instanceOfCrmCustomersCreateRequest(value: object): value is CrmCustomersCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CrmCustomersCreateRequestFromJSON(json: any): CrmCustomersCreateRequest {
    return CrmCustomersCreateRequestFromJSONTyped(json, false);
}

export function CrmCustomersCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CrmCustomersCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'email': json['email'],
    };
}

export function CrmCustomersCreateRequestToJSON(json: any): CrmCustomersCreateRequest {
    return CrmCustomersCreateRequestToJSONTyped(json, false);
}

export function CrmCustomersCreateRequestToJSONTyped(value?: CrmCustomersCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
    };
}

