/* tslint:disable */
/* eslint-disable */
/**
 * Quote Portal API
 * API documentation for Quote Portal
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegister
 */
export interface UserRegister {
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     * @type {string}
     * @memberof UserRegister
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegister
     */
    password: string;
}

/**
 * Check if a given object implements the UserRegister interface.
 */
export function instanceOfUserRegister(value: object): value is UserRegister {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function UserRegisterFromJSON(json: any): UserRegister {
    return UserRegisterFromJSONTyped(json, false);
}

export function UserRegisterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegister {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function UserRegisterToJSON(json: any): UserRegister {
    return UserRegisterToJSONTyped(json, false);
}

export function UserRegisterToJSONTyped(value?: UserRegister | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

