/* tslint:disable */
/* eslint-disable */
/**
 * Quote Portal API
 * API documentation for Quote Portal
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErpOrdersCreateRequest
 */
export interface ErpOrdersCreateRequest {
    /**
     * Customer name
     * @type {string}
     * @memberof ErpOrdersCreateRequest
     */
    customer: string;
    /**
     * Order total
     * @type {number}
     * @memberof ErpOrdersCreateRequest
     */
    total: number;
    /**
     * Order status
     * @type {string}
     * @memberof ErpOrdersCreateRequest
     */
    status: string;
}

/**
 * Check if a given object implements the ErpOrdersCreateRequest interface.
 */
export function instanceOfErpOrdersCreateRequest(value: object): value is ErpOrdersCreateRequest {
    if (!('customer' in value) || value['customer'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ErpOrdersCreateRequestFromJSON(json: any): ErpOrdersCreateRequest {
    return ErpOrdersCreateRequestFromJSONTyped(json, false);
}

export function ErpOrdersCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErpOrdersCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customer': json['customer'],
        'total': json['total'],
        'status': json['status'],
    };
}

export function ErpOrdersCreateRequestToJSON(json: any): ErpOrdersCreateRequest {
    return ErpOrdersCreateRequestToJSONTyped(json, false);
}

export function ErpOrdersCreateRequestToJSONTyped(value?: ErpOrdersCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer': value['customer'],
        'total': value['total'],
        'status': value['status'],
    };
}

