/* tslint:disable */
/* eslint-disable */
/**
 * Quote Portal API
 * API documentation for Quote Portal
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuotesSetStatusRequest
 */
export interface QuotesSetStatusRequest {
    /**
     * New status for the quote. e.g., 'Approved', 'Rejected'
     * @type {string}
     * @memberof QuotesSetStatusRequest
     */
    status: QuotesSetStatusRequestStatusEnum;
}


/**
 * @export
 */
export const QuotesSetStatusRequestStatusEnum = {
    PendingReview: 'Pending Review',
    Approved: 'Approved',
    Rejected: 'Rejected',
    ConvertedToOrder: 'Converted to Order'
} as const;
export type QuotesSetStatusRequestStatusEnum = typeof QuotesSetStatusRequestStatusEnum[keyof typeof QuotesSetStatusRequestStatusEnum];


/**
 * Check if a given object implements the QuotesSetStatusRequest interface.
 */
export function instanceOfQuotesSetStatusRequest(value: object): value is QuotesSetStatusRequest {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function QuotesSetStatusRequestFromJSON(json: any): QuotesSetStatusRequest {
    return QuotesSetStatusRequestFromJSONTyped(json, false);
}

export function QuotesSetStatusRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuotesSetStatusRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function QuotesSetStatusRequestToJSON(json: any): QuotesSetStatusRequest {
    return QuotesSetStatusRequestToJSONTyped(json, false);
}

export function QuotesSetStatusRequestToJSONTyped(value?: QuotesSetStatusRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

